server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
spring:
  application:
    name: eureka-server

management:
  tracing:
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0