server:
  port: 8081

spring:
  application:
    name: fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: user
    password: pass
#    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      client.id: fraud-service

logging:
  level:
    brave: DEBUG
    io:
      micrometer:
        tracing: DEBUG

management:
  tracing:
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0
#  zipkin:
#    endpoint: http://localhost:9411/api/v2/spans
