server:
  port: 8081

spring:
  application:
    name: fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: user
    password: pass
#    driver-class-name: org.postgresql.Driver