server:
  port: 8050

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
  main:
    web-application-type: reactive

management:
  tracing:
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
    sampling:
      probability: 1.0